---
apiVersion: v1
kind: Service
metadata:
  name: hackazon
spec:
  selector:
    app: hackazon
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackazon
spec:
  selector:
    matchLabels:
      app: hackazon
  replicas: 1
  template:
    metadata:
      labels:
        app: hackazon
    spec:
      containers:
      - name: hackazon
        image: ianwijaya/hackazon
        ports:
        - containerPort: 80
        - containerPort: 443
--- 
# cert is for ingress.ciaoremo.com
#  after the run you can check the cert with
#  k get secrets hack-tls -o jsonpath='{.data.tls\.crt}'|base64 -d >cert1 && openssl x509 -in cert1 -text -noout 
apiVersion: v1
kind: Secret
metadata:
  name: hack-tls
data:
  tls.crt: |-
      LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZxekNDQTVPZ0F3SUJBZ0lVSUxVWDVJQ013Q3RWeXJjVHV3WWtKaE15T0xjd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1pURUxNQWtHQTFVRUJoTUNWVk14Q3pBSkJnTlZCQWdNQWtOQk1SSXdFQVlEVlFRSERBbFFZV3h2SUVGcwpkRzh4RHpBTkJnTlZCQW9NQmxaTlYwRlNSVEVMTUFrR0ExVUVDd3dDU1ZReEZ6QVZCZ05WQkFNTURtbHZMbkpsCmJXOWhkbWt1WTI5dE1CNFhEVEl5TURnd09USXhORFF5TVZvWERUTXlNRGd3TmpJeE5EUXlNVm93WlRFTE1Ba0cKQTFVRUJoTUNWVk14Q3pBSkJnTlZCQWdNQWtOQk1SSXdFQVlEVlFRSERBbFFZV3h2SUVGc2RHOHhEekFOQmdOVgpCQW9NQmxaTlYwRlNSVEVMTUFrR0ExVUVDd3dDU1ZReEZ6QVZCZ05WQkFNTURtbHZMbkpsYlc5aGRta3VZMjl0Ck1JSUNJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBZzhBTUlJQ0NnS0NBZ0VBcXpUM3FrWVdTQnVsUGFWcXN5dkEKTVR3dU5nMDZ3SkZsQzVaZmZYNlIwRlBSUjV6TCthMUl1dDN4dnJVbEFQdjZad2o1MXJONFdNVnY5L1VzZlNpSwpicmRyUm82bE00OXBUN3dDWUJXZytSQ2FwZHJkQ0U1MVVoNjMzYU55U1E4bVpLdEdBVFZ2eWVpSkhocGlBUDMyCnlCYjI0UmgwN3o1YzZwN0wwYURrTFBFZzlyWkk2emVTTlpleVVYaGFEYmV0QXRwbHB6WEZTM0lnRGp3OFB4aUoKc0FqMUs4UDJGMTB2QmV5RUxEUGcwekNsSnJSRUtPUWdnUkFVU3pOaXZhWUdMVUV1NitrOEo3Qm5hTFpnSFN0WQp5Z2Vpd3BsemJ6ZFFvaUlvbXNZZVNrUE1CNHlBMlV2NlhvMVU0SE1jaloxaU1FR0xNeE1tVzFCbzMzK1dtRXAyCjhta2hTb2RuRjdvUmZhdkw1L1FsSnU5ZDF5aytrMjdrVzBOeGIzVUp2QmgwbmRCaE53dk9aUVZCUjVFQUFpV2MKUncya1lLVjR0VVllS0ZDYVpJUFBkUWtOenBOK2lBaGlyelptQjNDZmtlQnloQ01uMFVQR28xMFl6cHJlVENNbwp3ekZhWGRoems2WnVuQkZ4aFNIRitMRmxSRElGMFZ3K0g4VUlDVU9qWmhDb3RTT2o5bDJpd1pRSW5pL1Brc3hkCmc0SHZZQmt4T1I1SkREWXIzQXIyS3QyTkFFZ1hkZUY0NGRnclFnQ3p4QjR2OTA4YUxKWjdJU3NKcVhBSnlneCsKUVhSMlpqOFZOTVdjWFh3ck9zQlZDSjBtRENWMXozay9QTEVxSVBrZGNpNldwMlBuNFdiU1RSeDRrcDk3dmtoVAp3LzNDeWhGL1dlbTNUMEF3WHJjTUxTa0NBd0VBQWFOVE1GRXdIUVlEVlIwT0JCWUVGQmFNREJwOHQ4cFZqVDVnCjFQaTQyYm9MMk1vZE1COEdBMVVkSXdRWU1CYUFGQmFNREJwOHQ4cFZqVDVnMVBpNDJib0wyTW9kTUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dJQkFKelZVSm9PYWgwTCtDeWhES3d5d3F4dQpyRlFCU0lJSDFOM1Jkb3pGRmo2akZtQlNwYjg1ZzJwN2xJTy9kdDhtRUI0T2pwLzN4YVJCSmltQ3E2dEloVjdpClBzU25wemNJR0M3YjFaTXlsRysvQmxmWWV5Qkh1TnVoTlo1Q1p0L052R25GYVpqVllXWmhjYWh4VmFIMTFWQW8KVWFkZmFZbUlWVDVWc3laOTBuU2hTRmdOK2QxY1VFZm1YQlpsMnZwZlo2OGtKTW4xbGg4RzBWNnErNlVvVmRUcApIdHVWSnBvYVNxWFZCVHZ0VEVtaXZrQWZjMHhlSGpNN0VRMTdDRUF3cUh0YjNUWmhmTEJSWlNOREFyRnNGeStMClY2eDZuVWYzRFNhYzdCNnVSK1RjQ0w4ek1DZk9ta201cmtEUkJLT3h3L2ZZQk50OGVVN04yaHlOL2FjNTNPRDYKcERtRklPejcxbmZ6QWpmUlZrS1RxNDVtUm1TLy96ZHB2L0Z4N2Q0SEZmN2xtbkFTeFFXRU55bnRSSjBTeG9YVApTTDdCTEM1T0dMeXp0SDdQUFdoRG1RZkpxVENVYWJzRFc2QjVXQS9YMG1hL0FIZFBoTmJLbi9jYllKTkNwVHkvCnNCUjBSV0ZBMDVtbGVybmJseTVOTmxrdE9ET2lMajZvajQwbG5mMlJ4SzFIOVBZR1pMUklUOGFJeXU1Q1doeEIKL3Bnb1lRMXl1K0JCN0xzVTY2bGFSNWlZeE5UcWlQeDZ2S0FpU1FjQVRMdWdGZDJwSWovQVNIZjArTlBXK1RiKwo4dGlYZENMUDlMMlNscGYyTmxVM0JCUC9BdFh5bkVDazdnNUNueUNqNVBmd2U2SXJPd1BPYUx6cXByZHM2bmpnCjQyMmxpbktZSzg1c1dTT1pleWh5Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: |-
      LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUpRUUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQ1Nzd2dna25BZ0VBQW9JQ0FRQ3JOUGVxUmhaSUc2VTkKcFdxeks4QXhQQzQyRFRyQWtXVUxsbDk5ZnBIUVU5RkhuTXY1clVpNjNmRyt0U1VBKy9wbkNQbldzM2hZeFcvMwo5U3g5S0lwdXQydEdqcVV6ajJsUHZBSmdGYUQ1RUpxbDJ0MElUblZTSHJmZG8zSkpEeVprcTBZQk5XL0o2SWtlCkdtSUEvZmJJRnZiaEdIVHZQbHpxbnN2Um9PUXM4U0QydGtqck41STFsN0pSZUZvTnQ2MEMybVduTmNWTGNpQU8KUER3L0dJbXdDUFVydy9ZWFhTOEY3SVFzTStEVE1LVW10RVFvNUNDQkVCUkxNMks5cGdZdFFTN3I2VHduc0dkbwp0bUFkSzFqS0I2TENtWE52TjFDaUlpaWF4aDVLUTh3SGpJRFpTL3BlalZUZ2N4eU5uV0l3UVlzekV5WmJVR2pmCmY1YVlTbmJ5YVNGS2gyY1h1aEY5cTh2bjlDVW03MTNYS1Q2VGJ1UmJRM0Z2ZFFtOEdIU2QwR0UzQzg1bEJVRkgKa1FBQ0paeEhEYVJncFhpMVJoNG9VSnBrZzg5MUNRM09rMzZJQ0dLdk5tWUhjSitSNEhLRUl5ZlJROGFqWFJqTwptdDVNSXlqRE1WcGQySE9UcG02Y0VYR0ZJY1g0c1dWRU1nWFJYRDRmeFFnSlE2Tm1FS2kxSTZQMlhhTEJsQWllCkw4K1N6RjJEZ2U5Z0dURTVIa2tNTml2Y0N2WXEzWTBBU0JkMTRYamgyQ3RDQUxQRUhpLzNUeG9zbG5zaEt3bXAKY0FuS0RINUJkSFptUHhVMHhaeGRmQ3M2d0ZVSW5TWU1KWFhQZVQ4OHNTb2crUjF5THBhblkrZmhadEpOSEhpUwpuM3UrU0ZQRC9jTEtFWDlaNmJkUFFEQmV0d3d0S1FJREFRQUJBb0lDQUNHY1dtckJLNnFvVXI1UmRTc0xrY1dZCnJQSExreGN1OUFsY1VnN1BCRTFEeHpncDNobDhIV1VpSVUxeFBueDgrMkd5NzJsby9sMWZGV1kyYWErQWYvelEKWVcwT24vd0pVWUZueFllYmQyaXVDODQzczJEb0Zqd3k3NkhCYnJSTkZ4cDRUVnY3WTZEZDE5MWpESTVwVFVObQp6cnpPRWxiTmhXeENGSDFvK3FLZ0MvcWpPcG1DNVY5RUVxdlAxczRPbXhhT1RacVFBZFdYNkJjaldDaUM1clQ2CmJUZFVWMEdxOTRwUUxucUhETUlwTUtMeWpOY0NRaWRVUXNlb3BOL2FjaWY4UGZ2dVkvTGV2TTVmejJxcWtkbkgKdWZvK0tkMVJuTERYeCtUcXRCT2NUN2ZEcTUvOVBIL0hlenc5SFFQb085aUJaWlIzVS9abFNORm51T2JZNTVUSgpMUmc2b0w3bWU1R2ZxT0VYNnpRQldxRHlDOWVPNDZjZUtqdjZqMDhOSkVxZzM0dzRWYVlGeklHZjlRdkNSb0FOCkVGaHlYRjYydDI3U2xJWkNhU1lkalAzWHNTZllDVFpQVFhiOGoxYWx4Q2pWTm5zWUZTU2tGL2xVek9YYVhhenAKM0pzM0kxTE5VSTZaVXhXdVI5WndWeE9BeXNQNjdxTzVEWnU0VlhtK2l5RlhHWEZtcUQyTFZUWjVLSmREQU0vUAo5bUxydGxGcFFWQ3BhMFVJOTFkdk05TjAzY3NBZTVib1VnWU5HZTBBMng2TlpSL1FBWTd3bHczL0sybmNPNC85Ck1FT0RYVEgxcURFTnRqUjFlcDlkb09IcURYbXZEbDcrWEpDeHBUdzNERFVRUUxGT3pqZmZNaHovU0FTU21HNmcKT1YxWDYxTWlqREREaGZsM2luOEpBb0lCQVFEYVM2eWdlcTB6ZlIxczRHNythVXMrdVVtM2gwenZkVGtjOWE5aApKdmJXY29EMWM5RHFVbHZRdnpxMlc5MHZkSm54QTF1M3laY2N5UlVSajJNbDgySEpHWXNjSUQ3a1VVdHBHRlFVCjYvUHUxU1VQaXFOTmxLZG9UZm9qNDFHbXplbTdEN0x6dmRrNTdSVlNpY3JZcURSeUZvc2UzUG4xc2ErRHIveGsKL2dDdThMUkd5ZVdFWkh1RjBZRFRPOWJINVNhN2ViUlRRRW81ajFnYXZvREkxYXlocE5GVGVISkt5cHh0dEVzdApEc3daNHMxbVJoR09ya3FGd2lOMXJvUDhqTkRpQTJlcXFQN3RYSjY4RzFJTDE0M2VucFh1UnZNQ3R2V09zRkZKCjlDRmMxT0hscXFYUm5wUmx6T3hvS2I1Wm1RMnZTZ29BdUFodmdWMklWcUo2M2lkN0FvSUJBUURJeHk3aFN3U00KQmF0dSsyQWNyK0dsN09TOWxzVlpYYjR3ZkJzSVpqaDBjUHhSMUtva2VNUURUNlJEbTBhYUJseUpPSnQvZWRuYQpHUkxqU2dZTE43WlFwVnpOVGlOa1JwYXdkTzY3U0VRdlBhY29VaWtFRkRRSzA0NXpSbUJxTjhQSWVqMmZONmpTClpMZDArUVMyNjNPZWxmK2lOMjVFeWs1dmp4eGtEZVZJSnpFL3BaRUdrNkVuZ24xclBYMmdsVytwa0k0Qk5mUnUKOVVjc2xJRnF0Y3VWbEZLWkVYZHRBUG9XQ3BoemE4Z1dtc1o5NkFUTmJ3WDFiUjRtR2s3ZExTcldMTWhPbThkUgpUVUxlOVNuYS9YRlpBZldVZzVidVVFa2NIaEF2K29VUWR4TUxSdDh3YzNXWFpGOTVGTGY0cUhZNVRSQnM3aGprClJ2MTJuTFhNUndxckFvSUJBR3ZuV2laZFhYNEZDMldGTHZoTS9lZThXU2NDRjFLS1pEZmZiZGlkRlFoOXd5Y1IKSDZTa0gwUjVNa0Z2K1U1NjJabGI2cHRYWjMzUUc3ejVYcTRrdHlKYm9QcS9LYmRjUStWb0pDL1BUbDJ4T0VlTgpaUmwxTUtjTFhHa2U5WDU1YkY2TjdRdzB2TXE0V1lEYUljMmtuNEFCaXJVdno5TFdDUWNVRjdPb0pwaFMzUm5jCnRMb1RuVWRSZnRkclRjaXppY2pENlJINXhuYmJWMWFvOGluVURTZzl1MGNDVTZTS3NIWTkxNmNuR0ZaM1dNYUUKUGl1RUZjdzJZYWJMSSt6VGduRWw4N2xWSGVZZ2tVbzBTd01WZ3NnWEpjK0pmSmZMN21lZzJoMnZNa3FiNUNuTgpoM2V0Wm5kSHExZjF3bVN4bGlVZWVRRlA5c04vYzhkdjQ1TE9lejhDZ2dFQUU3bjJNaTV6c09veHNNTEQ2NjJnCkp2UkNlUm9pSTZpaE1oUlBkNkRMZFMxUXJSMk81ZXh6bmJ1cWNQWUZsc1ovT3dBenp1K0M1dm5Gc0UwcWtObVYKY1JEK01ERzRLbmNCQVM5TDhWeWxUbHJwWEgzT0I5ZVFVV3Y5dC9lM0sxaDFSUEkxc2JuL1BVU2wvYmtsckc4dgp1ZW9VNXJRNWdrcTZNQjNJZFZBa01kV2Y4aGZyU3RFZ2FVaFoyRHAvYUZLbVdPdVorQ1o3OEpicXVrZVErNUlICkFaaEVFVVAxRHVHa3NKdXo1TXMzS25sa2ZTUlpySEYzRFdqK0tGSTNZMlczcXJsVnFOdUhWc2FYaGw1aUVXRUwKVE9welhYY2NVaWZUTnc4QkdpV3NBelVmeXVEWXR1THhMOEd0MjdDY2JyTG1nclMrbzJVMVR1Qm1zTXV1MVBZNQo1d0tDQVFCL2VuRnpNK0VZNDZzazk5K1o2MjQ4ZStxdlEwbk5oRXhTTXlIZ01aMmkrTEJzUlhoZmorT2lobWxZCnA4aXZ1MjA4ZUhiYkloUWM2MFBHbnUwY25iVDE0aW50Rkl0bkRNSXFzTXhIVDY0NFpoMjYvbTVxZEszUTIyV3YKV0dtMFo4ZkxPMURMbnNkM0pXdjl3Wm5WbGRNL3ByMm5YUHdDYnV4aGFEQ2FiUzZtdTVZdldvUzNpZDQ5QUtRcwp2M3RTbHFzRHJUMS9kdmlUaDBHNk5ZU1VaYUZPNWRCOUZhdmJnd1l6alhYM1VhL2ZDbFJ4K2xTSDVYcW5sZ3B1Ck1tQXBpRGxSWkxxZ0duS0htRlVMMm1VTGxYbmpHV0dLUVcyL0ltOXlEQmhLbXZrTFd1RlFidWVVRnJpcWRlTUkKRGJBcTI1WWgrWHh3MTZTU01UOHVjOGlTNmx6RQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
      

type: kubernetes.io/tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hacknp
spec:
  tls:
  - hosts:
     - hackazon.default.avi.com
    secretName: hack-tls
  rules:
    - host: hackazon.default.avi.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: hackazon
                port:
                  number: 80
